name: Deploy Node Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy project to EC2
        run: scp -r ./ ubuntu@${{ secrets.EC2_PUBLIC_IP }}:~/backend

      - name: Create .env on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} "
            cd ~/backend
            echo \"MONGO_URI=${{ secrets.MONGO_URI }}\" > .env
            echo \"CLOUD_NAME=${{ secrets.CLOUD_NAME }}\" >> .env
            echo \"API_KEY=${{ secrets.API_KEY }}\" >> .env
            echo \"API_SECRET=${{ secrets.API_SECRET }}\" >> .env
            echo \"SMTP_USER=${{ secrets.SMTP_USER }}\" >> .env
            echo \"SMTP_PASS=${{ secrets.SMTP_PASS }}\" >> .env
            echo \"SMTP_HOST=${{ secrets.SMTP_HOST }}\" >> .env
            echo \"SMTP_PORT=${{ secrets.SMTP_PORT }}\" >> .env
            echo \"ROOT_URL=${{ secrets.ROOT_URL }}\" >> .env
            echo \"JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}\" >> .env
            echo \"JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}\" >> .env
            echo \"GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}\" >> .env
            echo \"GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}\" >> .env
          "

      - name: Build and run Docker on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} "
            cd ~/backend
            docker build -t sportify-backend .
            docker stop sportify-container || true
            docker rm sportify-container || true
            docker run -d -p 8000:8000 --name sportify-container --env-file .env sportify-backend
          "
